version: '3'

services:
  cas_server:
    build: ./cas_server
    command: python3 manage.py runserver 0.0.0.0:80
    volumes:
      - ./cas_server:/code
    networks:
      app_net:
        ipv4_address: 172.28.1.1

  cas_app1:
    build: ./cas_app1
    command: python3 manage.py runserver 0.0.0.0:80
    volumes:
      - ./cas_app1:/code
    networks:
      app_net:
        ipv4_address: 172.28.1.2

  cas_app2:
    build: ./cas_app2
    command: npm run start
    volumes:
      - ./cas_app2:/usr/src/app
    networks:
      app_net:
        ipv4_address: 172.28.1.3

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
